add_newline = true
command_timeout = 500

format = """
[](blue)\
$directory\
[](bg:purple fg:blue)\
$git_branch\
$git_status\
[](purple) \
$character"""

[character]
error_symbol = "[✗](bold red)"
success_symbol = "[❯](bold purple)"

[directory]
format = "[ $path ]($style)"
style = "bg:blue fg:black bold"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
format = "[ $symbol$branch ]($style)"
style = "bg:purple fg:black"
symbol = " "

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "bg:purple fg:black"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
conflicted = "="
up_to_date = ""
untracked = "?"
modified = "!"
stashed = "$"
staged = "+"
renamed = "»"
deleted = "✘"
