add_newline = true
command_timeout = 200
format = """
$directory\
$git_branch\
$git_status\
$fill\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = " "

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
format = "[ $path ]($style)"
style = "bold bg:#7aa2f7 fg:#1a1b26"
truncation_length = 3
truncation_symbol = "…/"
read_only = " 󰌾"

[git_branch]
format = "[ $symbol$branch ]($style)"
style = "bold bg:#9ece6a fg:#1a1b26"
symbol = " "

[git_status]
format = "[$all_status$ahead_behind]($style)"
style = "bold bg:#e0af68 fg:#1a1b26"
ahead = " ⇡${count}"
behind = " ⇣${count}"
diverged = " ⇕⇡${ahead_count}⇣${behind_count}"
conflicted = " ="
untracked = " ?"
modified = " !"
stashed = " $"
staged = " +"
renamed = " »"
deleted = " ✘"

[cmd_duration]
format = "[ 󰔚 $duration ]($style)"
style = "bold bg:#bb9af7 fg:#1a1b26"
min_time = 2000
